version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      - redis
    env_file:
      - .env

  worker:
    build: ./worker
    volumes:
      - ./worker:/usr/src/app
      - /usr/src/app/node_modules
      - ./storage:/usr/src/app/storage
    depends_on:
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mcp_audit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: