name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          context: ./mcp-security-server/server
          file: ./mcp-security-server/server/Dockerfile
          push: true
          tags: your-dockerhub-username/mcp-security-server:latest

      - name: Build and push worker
        uses: docker/build-push-action@v2
        with:
          context: ./mcp-security-server/worker
          file: ./mcp-security-server/worker/Dockerfile
          push: true
          tags: your-dockerhub-username/mcp-security-worker:latest